version: '3.4'

networks:
  internet:
    driver: bridge
  local:
    driver: bridge
    internal: true
    
x-logging: 
  main: &mainlog
    options:
      max-size: 50m
      
services:
  nginx:
    build: 
      context: ./nginx
      args:
        NGINX_VERSION: $NGINX_VERSION
    restart: on-failure
    depends_on:
     - wordpress
     - phpmyadmin
    ports:
     - "80:80"
     - "8080:8080"
    networks:
      - internet
      - local
    logging: *mainlog

  wordpress:
    image: wordpress:$WP_VERSION
    restart: on-failure
    environment:
     - WORDPRESS_DB_HOST=$DB_HOST:$DB_PORT
     - WORDPRESS_DB_USER=$WP_DB_USER 
     - WORDPRESS_DB_PASSWORD=$WP_DB_PASS
    networks:
      - internet
      - local
    logging: *mainlog

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:$PMA_VERSION
    restart: on-failure
    environment:
     - PMA_HOST=$DB_HOST
     - PMA_PORT=$DB_PORT
    networks:
      - local
    logging: *mainlog

  mysql:
    build: 
      context: ./mysql
      args:
        MYSQL_IMAGE: $MYSQL_IMAGE
        MYSQL_VERSION: $MYSQL_VERSION
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - local
    logging: *mainlog
