#!/bin/bash
set -eou pipefail

command="${1:-}"
commands="update, ansible, env, run, build, exec, restart, logs, stop"
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
layer_dir="$(dirname "$dir")"
base_dir="$(dirname "$layer_dir")"

CYAN='\033[0;36m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -z "$base_dir" ] || [ "$base_dir" = "/" ]; then
    msg="This project must be in a directory structure of type [base_dir]/[layer_dir]/[this_repo]"
    msg="$msg with base_dir different than '' or '/'"
    echo -e "${RED}${msg}${NC}"
    exit 1
fi

if [ -z "$command" ]; then
    echo -e "${RED}No command passed (valid commands: $commands)${NC}"
    exit 1
fi

pod_layer_dir="$base_dir/pod/lrd-pod"
app_layer_dir="$dir"

if [ "$command" = "update" ] || [ "$command" = "u" ]; then    
    echo -e "${CYAN}update - prepare...${NC}"
    $app_layer_dir/run prepare 
    echo -e "${CYAN}update - env...${NC}"
    $app_layer_dir/run env
    echo -e "${CYAN}update - build...${NC}"
    $app_layer_dir/run build
    echo -e "${CYAN}update - run...${NC}"
    $app_layer_dir/run run
    echo -e "${CYAN}update - composer${NC}"
    $app_layer_dir/run exec composer composer update
    echo -e "${CYAN}update - ended${NC}"
elif [ "$command" = "env" ]; then
    chmod +x $app_layer_dir/
    cp $pod_layer_dir/env/wordpress/.env $app_layer_dir/.env
    chmod +r $app_layer_dir/.env
else
    echo -e "${CYAN}running at pod_layer_dir ($pod_layer_dir)${NC}"
    $pod_layer_dir/run ${@}
fi