#!/bin/bash
set -eou pipefail

command="${1:-}"
commands="update, exec, logs, stop"
dir="$(cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")" && pwd)"
dev_dir="$(dirname "$dir")"
base_dir="$(dirname "$dev_dir")"

CYAN='\033[0;36m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -z "$base_dir" ] || [ "$base_dir" = "/" ]; then
    msg="This project must be in a directory structure of type [base_dir]/[dev_dir]/[this_repo]"
    msg="$msg with base_dir different than '' or '/'"
    echo -e "${RED}${msg}${NC}"
    exit 1
fi

if [ -z "$command" ]; then
    echo -e "${RED}No command passed (valid commands: $commands)${NC}"
    exit 1
fi

ctl_layer_dir="$base_dir/ansible-manager"
pod_layer_dir="/main/dev/docker-main"
app_layer_dir="$dir"
env_name="wordpress-blog-local"

if [ "$command" = "update" ] || [ "$command" = "u" ]; then    
    echo -e "${CYAN}update - ansible...${NC}"
    $app_layer_dir/scripts/dev ansible 
    echo -e "${CYAN}update - env...${NC}"
    $app_layer_dir/scripts/dev env
    echo -e "${CYAN}update - build...${NC}"
    $app_layer_dir/scripts/dev build
    echo -e "${CYAN}update - run...${NC}"
    $app_layer_dir/scripts/dev run
    echo -e "${CYAN}update - ended${NC}"
elif [ "$command" = "ansible" ]; then
    $ctl_layer_dir/launch dev-cmd /root/r/w/$env_name/dev
elif [ "$command" = "env" ]; then
    chmod +x $app_layer_dir/
    cp $pod_layer_dir/env/wordpress/.env $app_layer_dir/.env
    chmod +r $app_layer_dir/.env
elif [ "$command" = "run" ]; then
    details="${2:-}"
    cd $pod_layer_dir/
    sudo docker-compose up -d --remove-orphans $details
elif [ "$command" = "build" ] || [ "$command" = "exec" ] || [ "$command" = "logs" ]; then
    cd $pod_layer_dir/
    sudo docker-compose ${@}
elif [ "$command" = "stop" ]; then
    $ctl_layer_dir/launch stop

    cd $pod_layer_dir/
    sudo docker-compose stop
else
    echo -e "${RED}Invalid command: $command (valid commands: $commands)${NC}"
    exit 1
fi